# Generated by Django 3.1.7 on 2021-03-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
    ]
