# Generated by Django 3.1.7 on 2021-03-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20210317_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='testertt@gmail.com', max_length=50, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=15, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='patronym',
            field=models.CharField(max_length=15, verbose_name='patronym'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=15, verbose_name='surname'),
        ),
    ]
