# Generated by Django 3.1.7 on 2021-03-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20210318_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='none', upload_to='images/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
