# Generated by Django 3.1.7 on 2021-03-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='person',
            name='patronym',
            field=models.CharField(max_length=20, verbose_name='patronym'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='surname'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('surname', 'name', 'patronym')},
        ),
    ]
