# Generated by Django 3.1.7 on 2021-03-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20210319_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='tet', upload_to='media/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('surname', 'name')},
        ),
        migrations.RemoveField(
            model_name='person',
            name='patronym',
        ),
    ]
