# Generated by Django 3.1.7 on 2021-03-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20210319_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='../static/homepage/images/Icon-user.png', upload_to='media/', verbose_name='image'),
        ),
    ]
