# Generated by Django 3.1.7 on 2021-03-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20210320_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='../static/homepage/images/Icon-user.png', upload_to='person_images/', verbose_name='image'),
        ),
    ]
